### PR TITLE
Clarify the two types of submission

### PR DESCRIPTION
**Pull request by manics**
Make it clearer that that one set of examples is for HCS, the other is for non-HCS.
Convert to Markdown for better display in GitHub.

### CODE REVIEW

**Comment by sbesson** [comment]
:+1: for clarifying. Two questions/comments:

- can the renaming be separated from the clarification to ease the review?
- I seem to remember the choice of txt over md was made by the original IDR team with the end-user in mind since this repo is downloaded by data submitters. If this is no longer a requirements, I am all in favor of moving to Markdown.

**Comment by manics** [comment]
I've forced pushed/updated

**Comment by joshmoore** [comment]
@manics @sbesson : I pushed a commit to clarify why experiment starts at B. Otherwise, :+1:

**Comment by sbesson** [comment]
Thanks both.

**Pull request merged**
